# Generated by Django 4.0.7 on 2022-09-20 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediamanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TinyMCEImage',
            new_name='Image',
        ),
    ]
